spring:
  liquibase:
    enabled: false
  security:
    user:
      name: user
      password: password
logging:
  level:
    root: debug
myapplication:
  tasks:
    enabled: true
    name: 'Moja nazwa'
mytask:
  prefix: 'My prefix'
  suffix: 'My suffix'